version: '3'
services:
  person-db:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=person
      - POSTGRES_USER=person
      - POSTGRES_DB=person
    ports:
      - 5432:5432
    networks:
      - postgres-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=matheusarcelino@emailteste.com
      - PGADMIN_DEFAULT_PASSWORD=Pgadmin123
    ports:
      - 16543:80
    depends_on:
      - person-db
    networks:
      - postgres-network            

networks:
  postgres-network:
    driver: bridge
