spring:
  application:
    name: grpc-person-service
  datasource:  
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/person
     username: person
     password: person
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/person
    user: person
    password: person
